import {
  pgTable,
  serial,
  text,
  integer,
  timestamp,
  jsonb,
  primaryKey,
  uniqueIndex,
  index,
  pgEnum,
} from "drizzle-orm/pg-core";
import { sql } from "drizzle-orm";

/**
 * `userId` / `ownerId` / `invitedByUserId` columns below are `text`, not a
 * native Postgres `uuid`, to match Better Auth's own `user.id` column type
 * (Better Auth generates text ids, not uuids). There is deliberately no
 * DB-level foreign key to Better Auth's `user` table (defined separately in
 * db/auth-schema.ts, generated by its own CLI — see package.json
 * `auth:generate`) to avoid migration-ordering coupling between the two
 * schema sources; referential integrity to `user` is enforced at the
 * application layer (see lib/permissions.ts), consistent with
 * data-model.md.
 */

export const projectRoleEnum = pgEnum("project_role", ["owner", "member"]);
export const invitationStatusEnum = pgEnum("invitation_status", [
  "pending",
  "accepted",
  "rejected",
  "cancelled",
]);
export const notificationTypeEnum = pgEnum("notification_type", ["invitation"]);

// --- Proyecto (data-model.md § Proyecto) ---
export const projects = pgTable("projects", {
  id: serial("id").primaryKey(),
  publicId: text("public_id").notNull().unique(),
  name: text("name").notNull(),
  description: text("description"),
  workItemPrefix: text("work_item_prefix").notNull(),
  nextWorkItemNumber: integer("next_work_item_number").notNull().default(0),
  ownerId: text("owner_id").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});

// --- Membresía (data-model.md § Membresía) ---
export const projectMembers = pgTable(
  "project_members",
  {
    projectId: integer("project_id")
      .notNull()
      .references(() => projects.id, { onDelete: "cascade" }),
    userId: text("user_id").notNull(),
    role: projectRoleEnum("role").notNull(),
    joinedAt: timestamp("joined_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [
    primaryKey({ columns: [table.projectId, table.userId] }),
    // The PK above only helps lookups keyed by projectId first — listMyProjects
    // filters by userId alone, which needs its own index at scale (SC-005 of 001).
    index("project_members_user_id_idx").on(table.userId),
  ],
);

// --- Invitación (data-model.md § Invitación, FR-012 de 001) ---
export const invitations = pgTable(
  "invitations",
  {
    id: serial("id").primaryKey(),
    publicId: text("public_id").notNull().unique(),
    projectId: integer("project_id")
      .notNull()
      .references(() => projects.id, { onDelete: "cascade" }),
    invitedEmail: text("invited_email").notNull(),
    invitedByUserId: text("invited_by_user_id").notNull(),
    status: invitationStatusEnum("status").notNull().default("pending"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    respondedAt: timestamp("responded_at", { withTimezone: true }),
  },
  (table) => [
    // Partial unique index: only one *pending* invitation per (project, email) — FR-012 of 001.
    uniqueIndex("invitations_pending_project_email_idx")
      .on(table.projectId, table.invitedEmail)
      .where(sql`${table.status} = 'pending'`),
  ],
);

// --- Notificación (data-model.md § Notificación) ---
export const notifications = pgTable(
  "notifications",
  {
    id: serial("id").primaryKey(),
    userId: text("user_id").notNull(),
    type: notificationTypeEnum("type").notNull(),
    payload: jsonb("payload").notNull(),
    readAt: timestamp("read_at", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [index("notifications_user_id_idx").on(table.userId)],
);

// --- Stage/Columna (data-model.md § Stage/Columna) ---
export const stages = pgTable(
  "stages",
  {
    id: serial("id").primaryKey(),
    publicId: text("public_id").notNull().unique(),
    projectId: integer("project_id")
      .notNull()
      .references(() => projects.id, { onDelete: "cascade" }),
    name: text("name").notNull(),
    position: integer("position").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [index("stages_project_id_idx").on(table.projectId)],
);

// --- Work Item (data-model.md § Work Item) ---
export const workItems = pgTable(
  "work_items",
  {
    id: serial("id").primaryKey(),
    projectId: integer("project_id")
      .notNull()
      .references(() => projects.id, { onDelete: "cascade" }),
    displayNumber: integer("display_number").notNull(),
    stageId: integer("stage_id")
      .notNull()
      .references(() => stages.id, { onDelete: "cascade" }),
    title: text("title").notNull(),
    description: text("description"),
    stakeholder: text("stakeholder"),
    position: integer("position").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [
    // getBoard (SC-005 of 001) filters/joins on both — a project with many
    // stages and Work Items would otherwise force a sequential scan.
    index("work_items_project_id_idx").on(table.projectId),
    index("work_items_stage_id_idx").on(table.stageId),
  ],
);

// --- Tag (data-model.md § Tag, catálogo por proyecto) ---
export const tags = pgTable(
  "tags",
  {
    id: serial("id").primaryKey(),
    projectId: integer("project_id")
      .notNull()
      .references(() => projects.id, { onDelete: "cascade" }),
    name: text("name").notNull(),
  },
  (table) => [
    uniqueIndex("tags_project_lower_name_idx").on(table.projectId, sql`lower(${table.name})`),
  ],
);

// --- WorkItemTag (data-model.md § WorkItemTag, unión N:N) ---
export const workItemTags = pgTable(
  "work_item_tags",
  {
    workItemId: integer("work_item_id")
      .notNull()
      .references(() => workItems.id, { onDelete: "cascade" }),
    tagId: integer("tag_id")
      .notNull()
      .references(() => tags.id, { onDelete: "cascade" }),
  },
  (table) => [
    primaryKey({ columns: [table.workItemId, table.tagId] }),
    index("work_item_tags_tag_id_idx").on(table.tagId),
  ],
);

// --- Log de Actividad de Work Item (constitution § Estándares de Producto y Datos › Auditoría) ---
export const workItemActivity = pgTable(
  "work_item_activity",
  {
    id: serial("id").primaryKey(),
    workItemId: integer("work_item_id")
      .notNull()
      .references(() => workItems.id, { onDelete: "cascade" }),
    type: text("type").notNull(),
    payload: jsonb("payload").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [index("work_item_activity_work_item_id_idx").on(table.workItemId)],
);
