import {
  pgTable,
  serial,
  text,
  integer,
  timestamp,
  jsonb,
  primaryKey,
  uniqueIndex,
  index,
  pgEnum,
  check,
  boolean,
  foreignKey,
  date,
  type AnyPgColumn,
} from "drizzle-orm/pg-core";
import { sql } from "drizzle-orm";
// Relative (not "@/") so drizzle-kit can load this file without the tsconfig path alias.
import { WORK_ITEM_LEVELS } from "../lib/work-item-fields";

/**
 * `userId` / `ownerId` / `invitedByUserId` columns below are `text`, not a
 * native Postgres `uuid`, to match Better Auth's own `user.id` column type
 * (Better Auth generates text ids, not uuids). There is deliberately no
 * DB-level foreign key to Better Auth's `user` table (defined separately in
 * db/auth-schema.ts, generated by its own CLI — see package.json
 * `auth:generate`) to avoid migration-ordering coupling between the two
 * schema sources; referential integrity to `user` is enforced at the
 * application layer (see lib/permissions.ts), consistent with
 * data-model.md.
 */

// 007-roles-permissions: `viewer` (read-only) joins `owner` and `member`. The
// permission matrix per role lives in lib/roles.ts — not in the database.
export const projectRoleEnum = pgEnum("project_role", ["owner", "member", "viewer"]);
export const invitationStatusEnum = pgEnum("invitation_status", [
  "pending",
  "accepted",
  "rejected",
  "cancelled",
]);
// 011-agent-access-mcp FR-011: "work_item_assigned" joins invitations in the same panel.
export const notificationTypeEnum = pgEnum("notification_type", ["invitation", "work_item_assigned"]);
// 008-work-item-fields (FR-002/FR-003): two fixed four-level scales. Built from
// WORK_ITEM_LEVELS, whose order is urgency order — Postgres sorts enums by
// declaration, so `ORDER BY priority` puts the most urgent first.
export const workItemPriorityEnum = pgEnum("work_item_priority", WORK_ITEM_LEVELS);
export const workItemSeverityEnum = pgEnum("work_item_severity", WORK_ITEM_LEVELS);

// --- Proyecto (data-model.md § Proyecto) ---
export const projects = pgTable("projects", {
  id: serial("id").primaryKey(),
  publicId: text("public_id").notNull().unique(),
  name: text("name").notNull(),
  description: text("description"),
  workItemPrefix: text("work_item_prefix").notNull(),
  nextWorkItemNumber: integer("next_work_item_number").notNull().default(0),
  ownerId: text("owner_id").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});

// --- Membresía (data-model.md § Membresía) ---
export const projectMembers = pgTable(
  "project_members",
  {
    projectId: integer("project_id")
      .notNull()
      .references(() => projects.id, { onDelete: "cascade" }),
    userId: text("user_id").notNull(),
    role: projectRoleEnum("role").notNull(),
    joinedAt: timestamp("joined_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [
    primaryKey({ columns: [table.projectId, table.userId] }),
    // The PK above only helps lookups keyed by projectId first — listMyProjects
    // filters by userId alone, which needs its own index at scale (SC-005 of 001).
    index("project_members_user_id_idx").on(table.userId),
    // FR-002/SC-006 of 007-roles-permissions: a project can never have two
    // owners, even if an action has a bug or two run concurrently. (The
    // "at least one owner" half is kept by the actions — no action removes
    // the owner role without granting it to another member in the same
    // transaction.)
    uniqueIndex("project_members_one_owner_idx")
      .on(table.projectId)
      .where(sql`${table.role} = 'owner'`),
  ],
);

// --- Invitación (data-model.md § Invitación, FR-012 de 001) ---
export const invitations = pgTable(
  "invitations",
  {
    id: serial("id").primaryKey(),
    publicId: text("public_id").notNull().unique(),
    projectId: integer("project_id")
      .notNull()
      .references(() => projects.id, { onDelete: "cascade" }),
    invitedEmail: text("invited_email").notNull(),
    invitedByUserId: text("invited_by_user_id").notNull(),
    // FR-008 of 007-roles-permissions: the role the invitee gets on accepting.
    // `DEFAULT 'member'` keeps invitations pending before this feature valid
    // and behaving exactly as before (FR-015), with no backfill.
    role: projectRoleEnum("role").notNull().default("member"),
    status: invitationStatusEnum("status").notNull().default("pending"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    respondedAt: timestamp("responded_at", { withTimezone: true }),
  },
  (table) => [
    // Partial unique index: only one *pending* invitation per (project, email) — FR-012 of 001.
    uniqueIndex("invitations_pending_project_email_idx")
      .on(table.projectId, table.invitedEmail)
      .where(sql`${table.status} = 'pending'`),
    // FR-002 of 007: an invitation never grants `owner` — that role is only
    // reachable through an ownership transfer.
    check("invitations_role_not_owner_check", sql`${table.role} <> 'owner'`),
  ],
);

// --- Notificación (data-model.md § Notificación) ---
export const notifications = pgTable(
  "notifications",
  {
    id: serial("id").primaryKey(),
    userId: text("user_id").notNull(),
    type: notificationTypeEnum("type").notNull(),
    payload: jsonb("payload").notNull(),
    readAt: timestamp("read_at", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [
    index("notifications_user_id_idx").on(table.userId),
    // The panel reads "this user's unread, newest first" (011-agent-access-mcp data-model.md).
    index("notifications_user_unread_idx")
      .on(table.userId, table.createdAt)
      .where(sql`${table.readAt} is null`),
  ],
);

// --- Stage/Columna (data-model.md § Stage/Columna) ---
export const stages = pgTable(
  "stages",
  {
    id: serial("id").primaryKey(),
    publicId: text("public_id").notNull().unique(),
    projectId: integer("project_id")
      .notNull()
      .references(() => projects.id, { onDelete: "cascade" }),
    name: text("name").notNull(),
    position: integer("position").notNull(),
    // FR-011 of 008-work-item-fields: a Work Item in a closing column is
    // closed (FR-012) — see work_items.closed_at for the invariant.
    isClosing: boolean("is_closing").notNull().default(false),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [index("stages_project_id_idx").on(table.projectId)],
);

// --- Área / Iteración (008-work-item-fields data-model.md) ---
// Two separate per-project catalogs with the same shape as `tags`: values are
// created inline from a Work Item and reused case-insensitively (FR-006). The
// client only ever sends names, resolved within the Work Item's project
// (lib/work-item-catalogs.ts), so an id from another project can't be assigned.
export const areas = pgTable(
  "areas",
  {
    id: serial("id").primaryKey(),
    projectId: integer("project_id")
      .notNull()
      .references(() => projects.id, { onDelete: "cascade" }),
    name: text("name").notNull(),
  },
  (table) => [uniqueIndex("areas_project_lower_name_idx").on(table.projectId, sql`lower(${table.name})`)],
);

export const iterations = pgTable(
  "iterations",
  {
    id: serial("id").primaryKey(),
    projectId: integer("project_id")
      .notNull()
      .references(() => projects.id, { onDelete: "cascade" }),
    name: text("name").notNull(),
  },
  (table) => [
    uniqueIndex("iterations_project_lower_name_idx").on(table.projectId, sql`lower(${table.name})`),
  ],
);

// --- Work Item (data-model.md § Work Item) ---
export const workItems = pgTable(
  "work_items",
  {
    id: serial("id").primaryKey(),
    projectId: integer("project_id")
      .notNull()
      .references(() => projects.id, { onDelete: "cascade" }),
    displayNumber: integer("display_number").notNull(),
    stageId: integer("stage_id")
      .notNull()
      .references(() => stages.id, { onDelete: "cascade" }),
    title: text("title").notNull(),
    description: text("description"),
    // 011-agent-access-mcp FR-001: at most one CURRENT member of this project
    // (replaces the free-text `stakeholder`). Enforced by the composite FK
    // below; null means "Unassigned".
    assigneeUserId: text("assignee_user_id"),
    position: integer("position").notNull(),
    // 005-work-item-relationships data-model.md § Work Item — nullable
    // self-FK; `onDelete: set null` is what makes deleting a parent leave
    // its children as orphans (FR-012 of 005) without any application code.
    parentWorkItemId: integer("parent_work_item_id").references((): AnyPgColumn => workItems.id, {
      onDelete: "set null",
    }),
    // 008-work-item-fields data-model.md § Work Item — all optional.
    priority: workItemPriorityEnum("priority"),
    severity: workItemSeverityEnum("severity"),
    // 012-work-item-discussion: optional estimate; spent time is derived from
    // work_item_time_entries so the two cannot drift apart.
    estimateMinutes: integer("estimate_minutes"),
    // `set null` is only defensive: no flow deletes a catalog value (FR-007),
    // and deleting the project already cascades to its Work Items.
    areaId: integer("area_id").references(() => areas.id, { onDelete: "set null" }),
    iterationId: integer("iteration_id").references(() => iterations.id, { onDelete: "set null" }),
    // Calendar days with no time (FR-009); string mode keeps them "YYYY-MM-DD"
    // instead of a Date at UTC midnight that shifts a day across time zones.
    startDate: date("start_date", { mode: "string" }),
    targetDate: date("target_date", { mode: "string" }),
    // Written ONLY by the system, via nextClosedAt (lib/work-item-closing.ts).
    // Invariant (SC-006): closed_at IS NOT NULL ⇔ this Work Item's stage has
    // is_closing = true. "Closed" itself is derived from the stage, not stored.
    closedAt: timestamp("closed_at", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [
    // getBoard (SC-005 of 001) filters/joins on both — a project with many
    // stages and Work Items would otherwise force a sequential scan.
    index("work_items_project_id_idx").on(table.projectId),
    index("work_items_stage_id_idx").on(table.stageId),
    // Listing a Work Item's children (005-work-item-relationships) filters on this.
    index("work_items_parent_work_item_id_idx").on(table.parentWorkItemId),
    // "Assigned to me" / agent search, and the FK check when a membership row is deleted.
    index("work_items_assignee_idx").on(table.projectId, table.assigneeUserId),
    // FR-005/FR-006/SC-004 of 011-agent-access-mcp: the assignee must be a member
    // of THIS project, and leaving the project unassigns. The migration's SQL is
    // edited by hand to `ON DELETE SET NULL ("assignee_user_id")` (Postgres 15+):
    // a plain SET NULL would also null `project_id`, which is NOT NULL. drizzle
    // can't express the column list; drizzle-kit diffs against its snapshot, not
    // the database, so the hand edit is never regenerated away.
    foreignKey({
      name: "work_items_assignee_member_fk",
      columns: [table.projectId, table.assigneeUserId],
      foreignColumns: [projectMembers.projectId, projectMembers.userId],
    }).onDelete("set null"),
    // FR-009 of 008-work-item-fields; updateWorkItem checks it first with a friendlier error.
    check(
      "work_items_dates_order_check",
      sql`${table.startDate} IS NULL OR ${table.targetDate} IS NULL OR ${table.targetDate} >= ${table.startDate}`,
    ),
    check("work_items_estimate_minutes_check", sql`${table.estimateMinutes} IS NULL OR ${table.estimateMinutes} BETWEEN 0 AND 600000`),
  ],
);

// 012-work-item-discussion: human conversation, separate from the audit log.
export const workItemComments = pgTable(
  "work_item_comments",
  {
    id: serial("id").primaryKey(),
    publicId: text("public_id").notNull().unique(),
    workItemId: integer("work_item_id").notNull().references(() => workItems.id, { onDelete: "cascade" }),
    authorUserId: text("author_user_id").notNull(),
    authorName: text("author_name").notNull(),
    body: text("body").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [
    index("work_item_comments_item_created_idx").on(table.workItemId, table.createdAt, table.id),
    check("work_item_comments_body_check", sql`length(btrim(${table.body})) BETWEEN 1 AND 10000`),
  ],
);

// Individual time entries preserve who logged the work; the total is a sum.
export const workItemTimeEntries = pgTable(
  "work_item_time_entries",
  {
    id: serial("id").primaryKey(),
    publicId: text("public_id").notNull().unique(),
    workItemId: integer("work_item_id").notNull().references(() => workItems.id, { onDelete: "cascade" }),
    authorUserId: text("author_user_id").notNull(),
    authorName: text("author_name").notNull(),
    minutes: integer("minutes").notNull(),
    note: text("note"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [
    index("work_item_time_entries_item_created_idx").on(table.workItemId, table.createdAt, table.id),
    check("work_item_time_entries_minutes_check", sql`${table.minutes} BETWEEN 1 AND 600000`),
    check("work_item_time_entries_note_check", sql`${table.note} IS NULL OR length(${table.note}) <= 500`),
  ],
);

// --- WorkItemRelatedLink (005-work-item-relationships data-model.md § WorkItemRelatedLink) ---
export const workItemRelatedLinks = pgTable(
  "work_item_related_links",
  {
    id: serial("id").primaryKey(),
    // By convention always the smaller of the two ids (enforced by the
    // Server Action, not the DB) so the pair (A, B) is the same row
    // regardless of which order the user picked the two Work Items in.
    workItemIdA: integer("work_item_id_a")
      .notNull()
      .references(() => workItems.id, { onDelete: "cascade" }),
    workItemIdB: integer("work_item_id_b")
      .notNull()
      .references(() => workItems.id, { onDelete: "cascade" }),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [
    uniqueIndex("work_item_related_links_pair_idx").on(table.workItemIdA, table.workItemIdB),
    index("work_item_related_links_b_idx").on(table.workItemIdB),
    check("work_item_related_links_distinct_check", sql`${table.workItemIdA} <> ${table.workItemIdB}`),
  ],
);

// --- Tag (data-model.md § Tag, catálogo por proyecto) ---
export const tags = pgTable(
  "tags",
  {
    id: serial("id").primaryKey(),
    projectId: integer("project_id")
      .notNull()
      .references(() => projects.id, { onDelete: "cascade" }),
    name: text("name").notNull(),
  },
  (table) => [
    uniqueIndex("tags_project_lower_name_idx").on(table.projectId, sql`lower(${table.name})`),
  ],
);

// --- WorkItemTag (data-model.md § WorkItemTag, unión N:N) ---
export const workItemTags = pgTable(
  "work_item_tags",
  {
    workItemId: integer("work_item_id")
      .notNull()
      .references(() => workItems.id, { onDelete: "cascade" }),
    tagId: integer("tag_id")
      .notNull()
      .references(() => tags.id, { onDelete: "cascade" }),
  },
  (table) => [
    primaryKey({ columns: [table.workItemId, table.tagId] }),
    index("work_item_tags_tag_id_idx").on(table.tagId),
  ],
);

// --- Log de Actividad de Work Item (constitution § Estándares de Producto y Datos › Auditoría) ---
export const workItemActivity = pgTable(
  "work_item_activity",
  {
    id: serial("id").primaryKey(),
    workItemId: integer("work_item_id")
      .notNull()
      .references(() => workItems.id, { onDelete: "cascade" }),
    type: text("type").notNull(),
    payload: jsonb("payload").notNull(),
    // 011-agent-access-mcp FR-034: who made the change and, if it came through
    // an AI agent, which one. `agent_name` is copied at write time so the
    // history stays readable if the OAuth client is renamed or deleted. Always
    // written through logActivity (lib/activity.ts); null on older rows.
    actorUserId: text("actor_user_id"),
    agentClientId: text("agent_client_id"),
    agentName: text("agent_name"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [index("work_item_activity_work_item_id_idx").on(table.workItemId)],
);

// --- Último uso de un agente (011-agent-access-mcp data-model.md § agent_last_used) ---
// Touched by app/api/mcp/route.ts at most once a minute per pair (FR-035).
// No FK to `user`, like every user_id column here (see the note at the top).
export const agentLastUsed = pgTable(
  "agent_last_used",
  {
    userId: text("user_id").notNull(),
    clientId: text("client_id").notNull(),
    lastUsedAt: timestamp("last_used_at", { withTimezone: true }).notNull(),
  },
  (table) => [primaryKey({ columns: [table.userId, table.clientId] })],
);
